/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

//import forme.video_igra.FrmKreirajVideoIgru;
//import forme.video_igra.FrmPrikazVideoIgara;
import forme.korisnik.FrmIzmeniPodatke;
import forme.korisnik.FrmUnaprediKorisnika;
import forme.film.FrmPregledOcena;
import forme.film.FrmObrisiFilm;
import forme.film.FrmOcenjivanjeFilmova;
import forme.film.FrmNajboljeOcenjeniFilmovi;
import domen.Korisnik;
import forme.film.FrmDodajFilm;
//import forme.prodavnica.FrmKreirajProdavnicu;
//import forme.prodavnica.FrmPrikazSvihProdavnica;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import util.Util;

/**
 *
 * @author pavlepavle
 */
public class FrmGlavna extends javax.swing.JFrame {

    private Korisnik ulogovaniKorisnik;

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna(Korisnik korisnik) {
        this.ulogovaniKorisnik = korisnik;
        //setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        srediFormu(korisnik);
        srediMeni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKorisnik = new javax.swing.JLabel();
        btnOdjava = new javax.swing.JButton();
        btnIzmeniProfil = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmFilm = new javax.swing.JMenu();
        jmiOcenjivanjeFilmova = new javax.swing.JMenuItem();
        jmiPregledOcena = new javax.swing.JMenuItem();
        jmiNajboljeOcenjeni = new javax.swing.JMenuItem();
        jmAdmin = new javax.swing.JMenu();
        jmiUnaprediKorisnika = new javax.swing.JMenuItem();
        jmiDodajFilm = new javax.swing.JMenuItem();
        jmiObrisiFilm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblKorisnik.setForeground(new java.awt.Color(255, 51, 51));
        lblKorisnik.setText("Prijavljeni korisnik: ");

        btnOdjava.setText("Odjavi se");
        btnOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjavaActionPerformed(evt);
            }
        });

        btnIzmeniProfil.setText("Izmeni profil");
        btnIzmeniProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniProfilActionPerformed(evt);
            }
        });

        jmFilm.setText("Film");

        jmiOcenjivanjeFilmova.setText("Ocenjivanje filmova");
        jmiOcenjivanjeFilmova.setToolTipText("");
        jmiOcenjivanjeFilmova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOcenjivanjeFilmovaActionPerformed(evt);
            }
        });
        jmFilm.add(jmiOcenjivanjeFilmova);

        jmiPregledOcena.setText("Pregled ocena");
        jmiPregledOcena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPregledOcenaActionPerformed(evt);
            }
        });
        jmFilm.add(jmiPregledOcena);

        jmiNajboljeOcenjeni.setText("Najbolje ocenjeni filmovi");
        jmiNajboljeOcenjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNajboljeOcenjeniActionPerformed(evt);
            }
        });
        jmFilm.add(jmiNajboljeOcenjeni);

        jMenuBar1.add(jmFilm);

        jmAdmin.setText("Admin");

        jmiUnaprediKorisnika.setText("Unapredi korisnika");
        jmiUnaprediKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnaprediKorisnikaActionPerformed(evt);
            }
        });
        jmAdmin.add(jmiUnaprediKorisnika);

        jmiDodajFilm.setText("Dodaj film");
        jmiDodajFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDodajFilmActionPerformed(evt);
            }
        });
        jmAdmin.add(jmiDodajFilm);

        jmiObrisiFilm.setText("Obrisi film");
        jmiObrisiFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiFilmActionPerformed(evt);
            }
        });
        jmAdmin.add(jmiObrisiFilm);

        jMenuBar1.add(jmAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnIzmeniProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOdjava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblKorisnik)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblKorisnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniProfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdjava)
                .addGap(194, 194, 194))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiOcenjivanjeFilmovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOcenjivanjeFilmovaActionPerformed
        try {
            new FrmOcenjivanjeFilmova(ulogovaniKorisnik).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiOcenjivanjeFilmovaActionPerformed

    private void jmiPregledOcenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPregledOcenaActionPerformed
        try {
            new FrmPregledOcena(this, true, ulogovaniKorisnik).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiPregledOcenaActionPerformed

    private void btnOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjavaActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da se odjavite?", "Odjava", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (odgovor == 0) {
            try {
                Kontroler.vratiInstancu().odjavi(ulogovaniKorisnik);
                JOptionPane.showMessageDialog(this, "Uspesno izlogovan", "Poruka", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
            new FrmLogovanje().setVisible(true);
        }
    }//GEN-LAST:event_btnOdjavaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Kontroler.vratiInstancu().odjavi(ulogovaniKorisnik);
            JOptionPane.showMessageDialog(this, "Uspesno izlogovan", "Poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jmiUnaprediKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnaprediKorisnikaActionPerformed
        try {
            new FrmUnaprediKorisnika(this, true).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska: "+ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiUnaprediKorisnikaActionPerformed

    private void jmiDodajFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDodajFilmActionPerformed
        try {
            new FrmDodajFilm().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju prodavnica!", "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiDodajFilmActionPerformed

    private void btnIzmeniProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniProfilActionPerformed
        try {
            new FrmIzmeniPodatke(this, true, ulogovaniKorisnik, lblKorisnik).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniProfilActionPerformed

    private void jmiNajboljeOcenjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNajboljeOcenjeniActionPerformed
        try {
            new FrmNajboljeOcenjeniFilmovi(this, true, ulogovaniKorisnik).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska: "+ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiNajboljeOcenjeniActionPerformed

    private void jmiObrisiFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiFilmActionPerformed
        try {
            new FrmObrisiFilm().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska: "+ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiObrisiFilmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniProfil;
    private javax.swing.JButton btnOdjava;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdmin;
    private javax.swing.JMenu jmFilm;
    private javax.swing.JMenuItem jmiDodajFilm;
    private javax.swing.JMenuItem jmiNajboljeOcenjeni;
    private javax.swing.JMenuItem jmiObrisiFilm;
    private javax.swing.JMenuItem jmiOcenjivanjeFilmova;
    private javax.swing.JMenuItem jmiPregledOcena;
    private javax.swing.JMenuItem jmiUnaprediKorisnika;
    private javax.swing.JLabel lblKorisnik;
    // End of variables declaration//GEN-END:variables

    private void srediFormu(Korisnik korisnik) {
        lblKorisnik.setText(lblKorisnik.getText() + korisnik.getKorisnickoIme());
    }

    private void srediMeni() {
        if (!ulogovaniKorisnik.getAdministrator()) {
            jmAdmin.setVisible(false);
        }
    }

}
