/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.korisnik;

import domen.Korisnik;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author pavlepavle
 */
public class FrmIzmeniPodatke extends javax.swing.JDialog {

    Korisnik k;
    JLabel lblKorisnik;
    /**
     * Creates new form FrmIzmeniPodatke
     */
    public FrmIzmeniPodatke(java.awt.Frame parent, boolean modal, Korisnik k, JLabel lblKorisnik) {
        super(parent, modal);
        initComponents();
        this.k = k;
        popuniPolja();
        this.lblKorisnik = lblKorisnik;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jpfSifra = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jpfSifraPonovo = new javax.swing.JPasswordField();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Forma za izmenu podataka korisnika");

        jLabel1.setText("Korisnicko ime:");

        jLabel2.setText("Sifra:");

        jLabel3.setText("Ponovi sifru:");

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpfSifraPonovo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpfSifra))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzmeni)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpfSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpfSifraPonovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmeni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        
        String staroKorisnickoIme = k.getKorisnickoIme();
        String korisnickoIme = txtKorisnickoIme.getText().trim();
        String sifra = "";
        String ponovljenaSifra = "";
        char[] nizSlova = jpfSifra.getPassword();
        for (int i = 0; i < nizSlova.length; i++) {
            sifra += nizSlova[i];
        }
        char[] nizSlovaPonovo = jpfSifraPonovo.getPassword();
        for (int i = 0; i < nizSlovaPonovo.length; i++) {
            ponovljenaSifra += nizSlovaPonovo[i];
        }

        Korisnik k1 = new Korisnik(k.getKorisnikID(), k.getKorisnickoIme(), k.getLozinka(), k.getAdministrator());
        try {
            if (!sifra.equals(ponovljenaSifra)) {
                throw new Exception("Sifra se ne poklapa!");
            }
            k1.setKorisnickoIme(korisnickoIme);
            k1.setLozinka(sifra);
            if(Kontroler.vratiInstancu().izmeniPodatkeKorisnika(k1,staroKorisnickoIme, this)){
                k.setKorisnickoIme(k1.getKorisnickoIme());
                k.setLozinka(k1.getLozinka());
            }
            lblKorisnik.setText("Prijavljeni korisnik: " + k1.getKorisnickoIme());
            dispose();
        } catch (Exception e) {
            System.out.println("Greska: " + e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jpfSifra;
    private javax.swing.JPasswordField jpfSifraPonovo;
    private javax.swing.JTextField txtKorisnickoIme;
    // End of variables declaration//GEN-END:variables

    private void popuniPolja() {
        txtKorisnickoIme.setText(k.getKorisnickoIme());
        jpfSifra.setText(k.getLozinka());
        jpfSifraPonovo.setText(k.getLozinka());
    }
}
