/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.korisnik;

import domen.Korisnik;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import kontroler.Kontroler;
import modeli_tabela.TblModelKorisnik;

/**
 *
 * @author pavlepavle
 */
public class FrmUnaprediKorisnika extends javax.swing.JDialog {

    /**
     * Creates new form FrmUnaprediKorisnika
     */
    public FrmUnaprediKorisnika(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngAdmin = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtKorisnici = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKorisnickoImeFilter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rbTrue = new javax.swing.JRadioButton();
        rbFalse = new javax.swing.JRadioButton();
        btnPonistiFilter = new javax.swing.JButton();
        btnUnapredi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jtKorisnici.setColumnSelectionAllowed(true);
        jtKorisnici.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtKorisnici);
        jtKorisnici.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel2.setText("Korisnicko ime:");

        txtKorisnickoImeFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKorisnickoImeFilterKeyReleased(evt);
            }
        });

        jLabel3.setText("Izbor administrator vrednosti:");

        btngAdmin.add(rbTrue);
        rbTrue.setText("True");

        btngAdmin.add(rbFalse);
        rbFalse.setText("False");

        btnPonistiFilter.setText("Ponisti filter");
        btnPonistiFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPonistiFilter)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbTrue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbFalse))
                            .addComponent(txtKorisnickoImeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKorisnickoImeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbTrue)
                        .addComponent(rbFalse)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnPonistiFilter)
                .addContainerGap())
        );

        btnUnapredi.setText("Unapredi");
        btnUnapredi.setEnabled(false);
        btnUnapredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnaprediActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUnapredi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnUnapredi)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPonistiFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiFilterActionPerformed

        TblModelKorisnik tmk = (TblModelKorisnik) jtKorisnici.getModel();
        tmk.ponistiFilter();
        txtKorisnickoImeFilter.setText("");
        btngAdmin.clearSelection();

    }//GEN-LAST:event_btnPonistiFilterActionPerformed

    private void txtKorisnickoImeFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKorisnickoImeFilterKeyReleased

        String unetaRec = txtKorisnickoImeFilter.getText().trim();
        TblModelKorisnik tmk = (TblModelKorisnik) jtKorisnici.getModel();
        //tmk.pretraziKorisnike(unetaRec, tmk.getListaKorisnika());
        if (rbTrue.isSelected()) {
            tmk.pretraziKorisnike(unetaRec, tmk.getKopijaListe(), 1);
        }
        if (rbFalse.isSelected()) {
            tmk.pretraziKorisnike(unetaRec, tmk.getKopijaListe(), 0);
        }
        if (!rbFalse.isSelected() && !rbTrue.isSelected()) {
            tmk.pretraziKorisnike(unetaRec, tmk.getKopijaListe(), -1);
        }

    }//GEN-LAST:event_txtKorisnickoImeFilterKeyReleased

    private void btnUnaprediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnaprediActionPerformed
        
        try {
            TblModelKorisnik tmk = (TblModelKorisnik) jtKorisnici.getModel();
            int i = jtKorisnici.getSelectedRow();
            Korisnik k =tmk.vratiKorisnika(i);
            k.setAdministrator(true);
            Kontroler.vratiInstancu().unaprediKorisnika(k);
            tmk.unaprediKorisnika(k);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUnaprediActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPonistiFilter;
    private javax.swing.JButton btnUnapredi;
    private javax.swing.ButtonGroup btngAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtKorisnici;
    private javax.swing.JRadioButton rbFalse;
    private javax.swing.JRadioButton rbTrue;
    private javax.swing.JTextField txtKorisnickoImeFilter;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {

        try {
            TblModelKorisnik tmk = new TblModelKorisnik(Kontroler.vratiInstancu().vratiListuKorisnika());
            jtKorisnici.setModel(tmk);
            jtKorisnici.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jtKorisnici.setCellSelectionEnabled(false);
            jtKorisnici.setRowSelectionAllowed(true);
            jtKorisnici.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
                    int j = jtKorisnici.getSelectedRow();
                    if (j!=-1) {
                        btnUnapredi.setEnabled(true);
                    } else {
                        btnUnapredi.setEnabled(false);
                    }
                }
            });
            //jtKorisnici.setSelectionMode();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }

    }
}
