/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.film;

import domen.Film;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import kontroler.Kontroler;
import modeli_tabela.TblModelFilm;

/**
 *
 * @author pavlepavle
 */
public class FrmObrisiFilm extends javax.swing.JFrame {

    /**
     * Creates new form FrmObrisiFilm
     */
    public FrmObrisiFilm() {
        initComponents();
        srediTabelu();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFilm = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtNazivFilma = new javax.swing.JTextField();
        jsGodina = new javax.swing.JSpinner();
        checkBoxNazivFilma = new javax.swing.JCheckBox();
        checkBoxGodina = new javax.swing.JCheckBox();
        btnFiltriraj = new javax.swing.JButton();
        btnPonistiFilter = new javax.swing.JButton();
        btnObrisiFilm = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtblFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblFilm);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtNazivFilma.setEnabled(false);

        jsGodina.setModel(new javax.swing.SpinnerNumberModel(1894, 1894, 2017, 1));
        jsGodina.setEnabled(false);

        checkBoxNazivFilma.setText("Naziv filma:");
        checkBoxNazivFilma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNazivFilmaActionPerformed(evt);
            }
        });

        checkBoxGodina.setText("Godina:");
        checkBoxGodina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxGodinaActionPerformed(evt);
            }
        });

        btnFiltriraj.setText("Filtriraj");
        btnFiltriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrirajActionPerformed(evt);
            }
        });

        btnPonistiFilter.setText("Ponisti filter");
        btnPonistiFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkBoxNazivFilma, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(checkBoxGodina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNazivFilma)
                            .addComponent(jsGodina, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPonistiFilter)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxNazivFilma)
                    .addComponent(txtNazivFilma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxGodina)
                    .addComponent(jsGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltriraj)
                    .addComponent(btnPonistiFilter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnObrisiFilm.setText("Obrisi film");
        btnObrisiFilm.setEnabled(false);
        btnObrisiFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiFilmActionPerformed(evt);
            }
        });

        btnDetalji.setText("Detalji");
        btnDetalji.setEnabled(false);
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiFilm)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiFilm)
                    .addComponent(btnDetalji)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxNazivFilmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNazivFilmaActionPerformed

        if (txtNazivFilma.isEnabled()) {
            txtNazivFilma.setEnabled(false);
        } else {
            txtNazivFilma.setEnabled(true);
        }
    }//GEN-LAST:event_checkBoxNazivFilmaActionPerformed

    private void checkBoxGodinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxGodinaActionPerformed

        if (jsGodina.isEnabled()) {
            jsGodina.setEnabled(false);
        } else {
            jsGodina.setEnabled(true);
        }
    }//GEN-LAST:event_checkBoxGodinaActionPerformed

    private void btnFiltrirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrirajActionPerformed

        String unetaRec = txtNazivFilma.getText().trim();
        int godina = (int) jsGodina.getValue();
        TblModelFilm tmf = (TblModelFilm) jtblFilm.getModel();

        if (!checkBoxNazivFilma.isSelected() && !checkBoxGodina.isSelected()) {
            JOptionPane.showMessageDialog(this, "Nije izabran nijedan kriterijum pretrage", "Pretraga filmova", JOptionPane.INFORMATION_MESSAGE);
        } else if (checkBoxNazivFilma.isSelected() && checkBoxGodina.isSelected()) {
            tmf.pretraziFilmove(unetaRec, godina, tmf.getKopijaListe(), -1);
        } else if (checkBoxNazivFilma.isSelected()) {
            tmf.pretraziFilmove(unetaRec, 0, tmf.getKopijaListe(), 1);
        } else if (checkBoxGodina.isSelected()) {
            tmf.pretraziFilmove(unetaRec, godina, tmf.getKopijaListe(), 0);
        }
    }//GEN-LAST:event_btnFiltrirajActionPerformed

    private void btnPonistiFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiFilterActionPerformed

        TblModelFilm tmf = (TblModelFilm) jtblFilm.getModel();
        tmf.ponistiFilter();
        txtNazivFilma.setText("");
        checkBoxGodina.setSelected(false);
        checkBoxNazivFilma.setSelected(false);
        txtNazivFilma.setEnabled(false);
        jsGodina.setEnabled(false);
    }//GEN-LAST:event_btnPonistiFilterActionPerformed

    private void btnObrisiFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiFilmActionPerformed
        try {
            TblModelFilm tmf = (TblModelFilm) jtblFilm.getModel();
            int i = jtblFilm.getSelectedRow();
            Film f = tmf.vratiFilm(i);
            Kontroler.vratiInstancu().obrisiFilm(f);
            tmf.obrisiFilm(f);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiFilmActionPerformed

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed
        try {
            TblModelFilm tmf = (TblModelFilm) jtblFilm.getModel();
            int i = jtblFilm.getSelectedRow();
            Film f = tmf.vratiFilm(i);
            new FrmDetaljiFilma(f, this, true).setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDetaljiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnFiltriraj;
    private javax.swing.JButton btnObrisiFilm;
    private javax.swing.JButton btnPonistiFilter;
    private javax.swing.JCheckBox checkBoxGodina;
    private javax.swing.JCheckBox checkBoxNazivFilma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsGodina;
    private javax.swing.JTable jtblFilm;
    private javax.swing.JTextField txtNazivFilma;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        try {
            TblModelFilm tmf = new TblModelFilm(Kontroler.vratiInstancu().vratiListuFilmova());
            jtblFilm.setModel(tmf);
            jtblFilm.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
                    int j = jtblFilm.getSelectedRow();
                    if (j!=-1) {
                        btnDetalji.setEnabled(true);
                        btnObrisiFilm.setEnabled(true);
                    } else {
                        btnDetalji.setEnabled(false);
                        btnObrisiFilm.setEnabled(false);
                    }
                }
            });
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Poruka o gresci", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void srediFormu() {
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(jsGodina, "#"); 
        jsGodina.setEditor(editor);
    }
}
